#!/usr/bin/env bash
# scripts/claude-agents.sh — write a Claude Code subagent definition per persona
# (TASK-059).
#
# For every Claude Code persona in AGENT_ROSTER.md except the Orchestrator (the
# founder picks that session's model at start), writes
# .claude/agents/<name-lowercase>.md with `model:` and `effort:` resolved from the
# persona's Model cell by bp_roster_model_for_name. Run on every session start by
# scripts/session-start.sh, so a roster edit or a new model family takes effect
# without anyone remembering to regenerate. .claude/ is gitignored: the files are
# per machine, like the roster they come from.
#
# A persona whose Model cell does not resolve gets NO file and an error naming it.
# Files this script wrote earlier for personas no longer on the roster are removed
# (they carry the marker line below); hand-written agent files are never touched.
# Exit 1 if any persona failed.
set -u
root="$(cd "$(dirname "$0")/.." && pwd)"
BP_CODE_ROOT="$root"
# shellcheck source=scripts/lib/state-dir.sh
. "$root/scripts/lib/state-dir.sh"
BP_STATE_ROOT="$(bp_state_root)" || exit 1
# shellcheck source=scripts/lib/roster.sh
. "$root/scripts/lib/roster.sh"

marker='<!-- generated by scripts/claude-agents.sh from AGENT_ROSTER.md -->'
dir="$BP_STATE_ROOT/.claude/agents"
mkdir -p "$dir" || exit 1
rows="$(bp_roster_rows "$BP_STATE_ROOT")" || exit 1

rc=0
written=" "
while IFS="$(printf '\t')" read -r role name backing _; do
  [ "$backing" = "Claude Code" ] || continue
  [ "$role" = "Orchestrator" ] && continue
  r="$(bp_roster_model_for_name "$BP_STATE_ROOT" "$name")" || { rc=1; continue; }
  model="$(printf '%s' "$r" | cut -f2)"
  effort="$(printf '%s' "$r" | cut -f3)"
  slug="$(bp_roster_slug "$name")"
  # A file this script did not write is the project's: keep it, say so.
  if [ -f "$dir/$slug.md" ] && ! grep -qxF "$marker" "$dir/$slug.md"; then
    echo "claude-agents: $slug.md is not generated (no marker) — kept; persona $name uses it as written"
    written="$written$slug.md "
    continue
  fi
  cat >"$dir/$slug.md" <<EOF
---
name: $slug
description: $role
model: $model
effort: $effort
---
$marker

You are $name, the $role persona on this project's team (AGENT_ROSTER.md).
EOF
  written="$written$slug.md "
  echo "claude-agents: $slug -> $model, effort $effort"
done <<EOF
$rows
EOF

for f in "$dir"/*.md; do
  [ -f "$f" ] || continue
  case "$written" in *" ${f##*/} "*) continue ;; esac
  grep -qxF "$marker" "$f" && rm -f "$f" && echo "claude-agents: removed ${f##*/} (no longer on the roster)"
done
exit "$rc"
